version: 0.2

phases:
  install:
    commands:
      - echo 'garbage'
  build:
    commands:
      - export ROOT=`pwd`
      - echo 'Compiling the Maven Code'
      - cd $ROOT
      - mkdir -p ~/.m2/repository && unzip mvn-app/maven-dependencies.zip -d ~/.m2/repository
      - cd mvn-app && mvn -o compile
artifacts:
  type: zip
  files:
  - 'mvn-app/target/**/*'
